../dut/defines.sv
../dut/axil_int.sv
../dut/mdriver_int.sv
../dut/masterif.sv
../dut/umem.sv
../dut/axi_master_wrapper.sv
../dut/instruction_parser.sv
../dut/lfsr5.sv
../dut/axi_mem.sv
../dut/memslave.sv
../dut/cpu.sv
../dut/sindrv.sv
../dut/design.sv
../dut/soc_top.sv
